openapi: 3.0.2
info:
  title: API to get students information
  description: |-
    <b>Document of API to get students information</b><br>
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1/
tags:
  - name: student
    description: API about student

paths:
  /students/:
    get:
      tags:
        - student
      description: |
        get all students information
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentsProlilesGetResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBadRequest"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseInternalServerError"
  /students/{student_id}/:
    get:
      tags:
        - student
      description: |
        get a student information
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentProfileGetResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBadRequest"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseInternalServerError"
components:
  schemas:
    StudentsProlilesGetResponse:
      type: object
      properties:
        students:
          type: array
          items:
            $ref: "#/components/schemas/StudentProfileGetResponse"
          description: all students information
    StudentProfileGetResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
          description: student ID
        name:
          type: string
          example: Yamada Taro
          description: student name
        age:
          type: integer
          example: 16
          description: age
        class:
          type: integer
          example: 1
          description: class number
    ErrorResponseBadRequest:
      title: ErrorResponseBadRequest
      type: object
      description: bad request error response
      properties:
        message:
          type: string
          description: Sample of error message
          example: Bad Request
      required:
        - code
        - message
    ErrorResponseInternalServerError:
      title: ErrorResponseInternalServerError
      type: object
      description: internal server error response
      properties:
        message:
          type: string
          description: sample of error message
          example: internal Server Error
      required:
        - message
